os: osx
language: objective-c
osx_image: xcode9.2
git:
  submodules: false
cache: false
before_install:
  - gem install xcpretty                      # to suppress build log from xcodebuild, workign with xcpretty-travis-formatter
  - gem install xcpretty-travis-formatter
  - gem install cocoapods -v '1.3.1'
  - git submodule update --init
  - pod install --repo-update
  - ./ci/scripts/versions.sh
before_script:
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/certs/potatso-development.cer.enc -d -a -out ci/certs/potatso-development.cer
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/certs/potatso-development.p12.enc -d -a -out ci/certs/potatso-development.p12
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/profiles/main-development.mobileprovision.enc -d -a -out ci/profiles/main-development.mobileprovision
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/profiles/ex-packettunnel-development.mobileprovision.enc -d -a -out ci/profiles/ex-packettunnel-development.mobileprovision
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/profiles/ex-todaywidget-development.mobileprovision.enc -d -a -out ci/profiles/ex-todaywidget-development.mobileprovision
  - ./ci/scripts/add_key.sh
  - ./ci/scripts/install_profiles.sh
script:
  - xcodebuild -workspace Potatso.xcworkspace -scheme Potatso -configuration "$XCODEBUILD_CONFIGURATION" -sdk "$XCODEBUILD_SDK" -arch arm64 -quiet | xcpretty -f `xcpretty-travis-formatter`